# Generated by Django 3.2.6 on 2021-08-06 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='left',
            name='left_vote',
        ),
        migrations.AddField(
            model_name='left',
            name='left_vote',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='right',
            name='right_vote',
        ),
        migrations.AddField(
            model_name='right',
            name='right_vote',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
