# Generated by Django 3.2.6 on 2021-08-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210806_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='left',
        ),
        migrations.AddField(
            model_name='post',
            name='left',
            field=models.ManyToManyField(to='feed.Left'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='right',
        ),
        migrations.AddField(
            model_name='post',
            name='right',
            field=models.ManyToManyField(to='feed.Right'),
        ),
    ]
