# Generated by Django 3.2.6 on 2021-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210806_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='right_vote',
        ),
        migrations.RemoveField(
            model_name='post',
            name='left',
        ),
        migrations.RemoveField(
            model_name='post',
            name='right',
        ),
        migrations.AddField(
            model_name='post',
            name='left_content',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='left_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='right_content',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='right_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Left',
        ),
        migrations.DeleteModel(
            name='Right',
        ),
    ]
