# Generated by Django 3.2.6 on 2021-08-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0004_auto_20210806_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='left_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='left_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='right_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='right_title',
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_title', models.CharField(default='', max_length=200)),
                ('right_content', models.CharField(default='', max_length=200)),
                ('right_vote', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_title', models.CharField(default='', max_length=200)),
                ('left_content', models.CharField(default='', max_length=200)),
                ('left_vote', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='left',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='feed.left'),
        ),
        migrations.AddField(
            model_name='post',
            name='right',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='feed.right'),
        ),
    ]
