# Generated by Django 3.2.6 on 2021-08-06 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0005_auto_20210806_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='left',
            name='left_vote',
        ),
        migrations.AddField(
            model_name='left',
            name='left_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='right',
            name='right_vote',
        ),
        migrations.AddField(
            model_name='right',
            name='right_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
