# Generated by Django 3.2.6 on 2021-08-06 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0007_auto_20210806_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='left',
            name='left_vote',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='right',
            name='right_vote',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
