# Generated by Django 3.2.6 on 2021-08-06 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20210806_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='left',
        ),
        migrations.RemoveField(
            model_name='post',
            name='right',
        ),
        migrations.AddField(
            model_name='left',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.post'),
        ),
        migrations.AddField(
            model_name='right',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.post'),
        ),
        migrations.AlterField(
            model_name='left',
            name='left_content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='left',
            name='left_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='right',
            name='right_content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='right',
            name='right_title',
            field=models.CharField(max_length=200),
        ),
    ]
