# Generated by Django 3.2.6 on 2021-08-06 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0010_auto_20210806_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='post',
        ),
        migrations.RemoveField(
            model_name='right',
            name='right_vote',
        ),
        migrations.AddField(
            model_name='post',
            name='left_content',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='left_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='left_vote',
            field=models.ManyToManyField(blank=True, related_name='left_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='right_content',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='right_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='right_vote',
            field=models.ManyToManyField(blank=True, related_name='right_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Left',
        ),
        migrations.DeleteModel(
            name='Right',
        ),
    ]
